### PR TITLE
Fix inconsistent state updates

### LINKED ISSUE #12: Stuck on spinner after balance history download
One minor thing. After I complete a balance history download, when I reopen the chrome extension I see this spinner doing nothing. I'd expect it to be back at the home screen or show the "Download complete" screen still

image

### PR DESCRIPTION
**Pull request by vanessa**
The issue seemed to be that the storages weren't picking up state changes when they were made from the background script. Fix by adding a listener to `chrome.storage.local.onChanged`.

Closes #12.

### CODE REVIEW

File: src/shared/storages/base.ts [hunk 1]
```diff
@@ -76,15 +71,21 @@ export function createStorage<D>(
...
     _emitChange();
   });
 
+  // This is called when the storage changes from the service worker
+  chrome.storage.local.onChanged.addListener((changes) => {
+    if (changes[key]) {
+      cache = { ...cache, ...changes[key].newValue };
+      _emitChange();
+    }
+  });
```
Comment (vanessa) [inline src/shared/storages/base.ts:87]: This is the main change of the PR; the others are more QOL-related.

**Review by masonwolters — APPROVED** [review]
